name: Render

on: push

jobs:
  render:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://pandoc/latex:latest
        with:
          args: -s -N --template eisvogel.tex --lua-filter ./svgbob.lua --filter pandoc-citeproc Rapport.md -o output/Rapport.pdf
      - uses: actions/upload-artifact@master
        with: 
          name: rendered
          path: rendered
