name: Render

on: push

jobs:
  render:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: mkdir rendered
      - uses: docker://opinon/pandoc_svgbob:latest
        with:
          args: ./compile.sh 
      - uses: actions/upload-artifact@master
        with: 
          name: rendered
          path: rendered
